# Generated by Django 3.2.13 on 2022-12-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('date', models.DateField(default=True)),
                ('book', models.ManyToManyField(choices=[('Tailoring', 'Tailoring'), ('Hair Style', 'Hair Style'), ('Heena', 'Heena'), ('Neckles', 'Neckles'), ('Hand ring', 'Hand ring'), ('Puredicurist', 'Puredicurist')], related_name='placed', to='beauty.Service')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='beauty.service')),
            ],
        ),
    ]
