# Generated by Django 3.2.13 on 2022-12-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_BOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='beauty.time_book'),
        ),
    ]
