# Generated by Django 3.2.13 on 2022-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_auto_20221204_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='book',
            field=models.ManyToManyField(choices=[('Tailoring', 'Tailoring'), ('Hair Style', 'Hair Style'), ('Heena', 'Heena'), ('Neckles', 'Neckles'), ('Hand ring', 'Hand ring'), ('Puredicurist', 'Puredicurist')], to='beauty.Service'),
        ),
    ]
