# Generated by Django 3.2.13 on 2022-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0003_alter_person_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default=False, max_length=70),
        ),
    ]
